import type {Metadata} from "next";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer"
import "./globals.css"
import { Quicksand, Lora, Merriweather, Barlow_Condensed, Libre_Baskerville} from 'next/font/google';

const quicksand = Quicksand({
  variable: '--font-quicksand'
})

const lora = Lora({
  variable: '--font-lora'
})

const merriweather = Merriweather({
  variable: '--font-merriweather'
})

const barlow_condensed = Barlow_Condensed({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-barlow_condensed'
})


export const metadata: Metadata = {
  title: "Apostolic Faith Church Sacramento",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" >
      <body>
        <div className={`${quicksand.variable} ${lora.variable} ${merriweather.variable} ${barlow_condensed.variable}`}>
          <Navbar />
          {children}
          <Footer />
       </div>
      </body>
    </html>
  )
}