import type {Metadata} from "next";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer"
import "./globals.css"
import { Quicksand } from 'next/font/google';

const quicksand = Quicksand({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-quicksand'
})

export const metadata: Metadata = {
  title: "Apostolic Faith Church Sacramento",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html className={`${quicksand.variable}`}lang="en">
      <body>
        <div>
          <Navbar />
          {children}
          <Footer />
       </div>
      </body>
    </html>
  )
}