import type {Metadata} from "next";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer"
import "./globals.css"


export const metadata: Metadata = {
  title: "Apostolic Faith Church Sacramento",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}